name: typing_tutior
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  art_sweetalert: ^0.0.5
  flutter:
    sdk: flutter
  audioplayers: ^0.20.1
  url_launcher: ^6.1.10
  dotted_border: ^2.0.0+3




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  footer: ^0.0.4
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/devloper_screen_images/logo.png
    - assets/devloper_screen_images/linkedin.png
    - assets/devloper_screen_images/DU_Logo.png
    - assets/devloper_screen_images/ASWDC.png
    - assets/splash_screen/typingSpeedLogo.jpg
    - assets/splash_screen/ASWDClogo.png
    - assets/images/index.png
    - assets/images/middle.png
    - assets/images/ring.png
    - assets/images/pinkey.png
    - assets/images/rightIndex.png
    - assets/images/rightMiddle.png
    - assets/images/rightRing.png
    - assets/images/rightPinkey.png
    - assets/images/space.png
    - assets/images/rightDefault.png
    - assets/images/leftDefault.png
    - assets/images/spaceLeft.png
    - assets/sound/buzzer.wav
    - assets/sound/buzzer-or-wrong-answer-20582.mp3
    - assets/keybord_image/toprow.png
    - assets/keybord_image/toprow4.png
    - assets/keybord_image/hometop.png
    - assets/keybord_image/homeRowtop.png
    - assets/keybord_image/homeRowSHIFT.png
    - assets/keybord_image/homeRowbottomRow.png
    - assets/keybord_image/homeRow.png
    - assets/keybord_image/BOTTOMtop.png
    - assets/keybord_image/bottomRow.png
    - assets/keybord_image/toprowshift.png
    - assets/splash_screen/ASWDClogo.png
    - assets/splash_screen/ic_logo.png
    - assets/splash_screen/splash_screen.png
    - assets/sound/sound_keyboard_wrong.ogg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
